In [3]:
import numpy as np
import pandas as pd

## Question 1 - Answer: '1.5.3'

In [4]:
pd.__version__

'1.5.3'

In [59]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

In [60]:
df.to_csv("hw1.csv")

## Question 2 - Answer: 10

In [6]:
df.shape[1]

10

In [7]:
df.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

In [8]:
df.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

## Question 3 - Answer: total_bedrooms

In [9]:
df.isnull().value_counts()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  population  households  median_income  median_house_value  ocean_proximity
False      False     False               False        False           False       False       False          False               False              20433
                                                      True            False       False       False          False               False                207
dtype: int64

In [10]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4 - Answer: 5

In [11]:
df["ocean_proximity"].nunique()

5

In [12]:
df["ocean_proximity"].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

## Question 5 - Answer: 259212

In [13]:
round(df[df["ocean_proximity"] == "NEAR BAY"]["median_house_value"].mean())

259212

## Question 6 - Answer: No

In [14]:
df.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

In [15]:
average_of_total_bedrooms = round(df["total_bedrooms"].mean(), 3)
print(f"average_of_total_bedrooms: {average_of_total_bedrooms}" )

average_of_total_bedrooms: 537.871


In [16]:
df["total_bedrooms"] = df["total_bedrooms"].fillna(538)

average_of_total_bedrooms_alrered = round(df["total_bedrooms"].mean(), 3)
print(f"average_of_total_bedrooms_alrered: {average_of_total_bedrooms_alrered}" )

average_of_total_bedrooms_alrered: 537.872


## Question 7 - Answer: 5.69922946

1. Select all the options located on islands.

In [17]:
island = df[df["ocean_proximity"] == "ISLAND"]
island

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

2. Select only columns housing_median_age, total_rooms, total_bedrooms.

In [18]:
island_filtered = island[["housing_median_age", "total_rooms", "total_bedrooms"]]
island_filtered

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

3. Get the underlying NumPy array. Let's call it X.

In [24]:
X = island_filtered.values
print(type(X))
X

<class 'numpy.ndarray'>


array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [26]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [43]:
XT = X.transpose()
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

OR

In [61]:
XT = X.T
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [64]:
XTX = np.dot(XT, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

5. Compute the inverse of XTX.

In [68]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

6. Create an array y with values [950, 1300, 800, 1000, 1300].

In [69]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [71]:
temp = np.dot(XTX_inv, X.T)
print(temp)

w = np.dot(temp, y)
w

[[-0.00825608 -0.00653208 -0.00232159  0.02565144  0.01204934]
 [-0.00165852  0.0011141   0.00139656 -0.00103215 -0.00110698]
 [ 0.00754365 -0.00301964 -0.00455125  0.00181685  0.00329418]]


array([23.12330961, -1.48124183,  5.69922946])

8. What's the value of the last element of w? Answer  5.69922946